---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/start_game":
    post:
      summary: Creates a game
      tags:
      - Games
      parameters: []
      responses:
        '201':
          description: Game created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                game:
                  properties:
                    players_attributes:
                      type: object
                      example:
                      - name: Jim
                      - name: Pam
  "/get_scores/{id}":
    get:
      summary: Retrieves a game
      tags:
      - Games
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: name found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
        '404':
          description: Game not found
  "/rounds/{id}":
    put:
      summary: Updates a round
      tags:
      - Rounds
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: round updated
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                round:
                  properties:
                    pins:
                      type: integer
                      example: 4
                    roll:
                      type: integer
                      example: 1
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
